### ISSUE TITLE
problems with onStick = true / compiling rust 

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#205]
I tried to test onstick mode so I:

1. Created vlans in netplan
```
/opt/libreqos/src# cat /etc/netplan/00-installer-config.yaml 
# This is the network config written by 'subiquity'
network:
  version: 2
  ethernets:
    ens18:
      addresses:
      - 10.100.0.6/24
      routes:
      - to: default
        via: 10.100.0.254
      nameservers:
        addresses:
        - 46.151.191.151
        - 46.151.191.5
        search: []
    ens16np0:
      dhcp4: no
  vlans:
    vlan.800:
      id: 800
      link: ens16np0
      dhcp4: no
    vlan.900:
      id: 900
      link: ens16np0
      dhcp4: no
```

I see it correctly in: `ip a s`
```
4: vlan.800@ens16np0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN group default qlen 1000
    link/ether 1c:34:da:47:32:94 brd ff:ff:ff:ff:ff:ff
5: vlan.900@ens16np0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state LOWERLAYERDOWN group default qlen 1000
    link/ether 1c:34:da:47:32:94 brd ff:ff:ff:ff:ff:ff
```

2. Turning an VLAN Offload
cat /usr/local/sbin/offloadOff.sh 
```
#!/bin/sh
ethtool --offload ens16np0 gso off tso off lro off sg off gro off
ethtool -K ens16np0 rxvlan off
```

I set ispConfig.py as:
```
# Interface connected to core router
interfaceA = 'ens16np0'

# Interface connected to edge router
interfaceB = 'ens16np0'

# WORK IN PROGRESS. Note that interfaceA determines the "stick" interface
# I could only get scanning to work if I issued ethtool -K enp1s0f1 rxvlan off
OnAStick = True
# VLAN facing the core router
StickVlanA = 800
# VLAN facing the edge router
StickVlanB = 900
```

3. Compiling rust libraries by command: ./build_rust.sh
I got few compiling errors/warnings: http://kłopotek.pl/rust-libraries-txt

4. Running LibreQoS.py gives me an error
```
lqosd is running
refreshShapers starting at 20/01/2023 14:01:49
First time run since system boot.
Validating input files 'ShapedDevices.csv' and 'network.json'
network.json passed validation
ShapedDevices.csv passed validation
Backed up good config as lastGoodConfig.csv and lastGoodConfig.json
NIC queues:			16
CPU cores:			16
queuesAvailable set to:	16
On-a-stick override dividing queues
Generating parent nodes
Using binpacking module to sort circuits by CPU core
Finished binpacking
Generated parent nodes created
Up ParentClassID: 0x9:
ClassMinor: 0x3
Up ParentClassID: 0xa:
ClassMinor: 0x3
Up ParentClassID: 0xb:
ClassMinor: 0x3
Up ParentClassID: 0xc:
ClassMinor: 0x3
Up ParentClassID: 0xd:
ClassMinor: 0x3
Up ParentClassID: 0xe:
ClassMinor: 0x3
Up ParentClassID: 0xf:
ClassMinor: 0x3
Up ParentClassID: 0x10:
ClassMinor: 0x3
Error: Cannot delete qdisc with handle of zero.
Error: Cannot delete qdisc with handle of zero.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:13:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/opt/libreqos/src/./LibreQoS.py", line 1297, in <module>
    refreshShapers()
  File "/opt/libreqos/src/./LibreQoS.py", line 787, in refreshShapers
    clear_ip_mappings() # Use the bus
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
