### ISSUE TITLE
Web UI config network interface name mismatch

### ISSUE THREAD

**Issue by thebracket** [LibreQoE/LibreQoS#313]
User selected `enp33s0f0` etc:
![image](https://user-images.githubusercontent.com/14896751/228620832-666d0c0d-a28b-45b4-8ee0-8aac1c723b92.png)

And wound up with a bridge with the wrong interface names:
```toml
[bridge]
use_xdp_bridge = true
interface_mapping = [
       { name = "enp49s0f1", redirect_to = "enp49s0f0", scan_vlans = false },
       { name = "enp49s0f0", redirect_to = "enp49s0f1", scan_vlans = false }
]
vlan_mapping = []
```
